#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const CWD = process.cwd();
const CLAUDE_DIR = path.join(CWD, '.claude');
const CLI_PATH = path.join(CWD, 'scripts', 'cli.js');
const DOCS_PATH = path.join(CLAUDE_DIR, 'codebase-docs.md');

// Colors
const BOLD = '\x1b[1m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RED = '\x1b[31m';
const CYAN = '\x1b[36m';
const RESET = '\x1b[0m';

function parseCliCommands() {
  if (!fs.existsSync(CLI_PATH)) return [];
  const content = fs.readFileSync(CLI_PATH, 'utf-8');
  
  // Extract usage() function content
  const usageMatch = content.match(/function usage\(\)\s*\{([\s\S]*?)\}/);
  if (!usageMatch) return [];

  const usageBody = usageMatch[1];
  const lines = usageBody.split('\n');
  const commands = [];

  lines.forEach(line => {
    // Look for lines containing "npx claudient <cmd> [desc]"
    const match = line.match(/npx claudient\s+([a-zA-Z0-9_\-\[\]|<>:\s]+?)\s{2,}(.*)/);
    if (match) {
      commands.push({
        command: `npx claudient ${match[1].trim()}`,
        description: match[2].trim()
      });
    }
  });

  return commands;
}

function main() {
  console.log(`\n${BOLD}${CYAN}══════════════════════════════════════════════════════════════════════════════════${RESET}`);
  console.log(`  ${BOLD}${CYAN}THE HISTORIAN: ZERO-DRIFT DOCS HOOK${RESET}`);
  console.log(`  ${YELLOW}Automatically syncing CLI commands structure to codebase documentation...${RESET}`);
  console.log(`${BOLD}${CYAN}══════════════════════════════════════════════════════════════════════════════════${RESET}\n`);

  const commands = parseCliCommands();
  console.log(`Extracted ${commands.length} CLI command structures from scripts/cli.js.\n`);

  let docContent = `# Claudient CLI Command Reference Documentation\n\n`;
  docContent += `*This reference document is automatically generated by the Zero-Drift Docs Hook to prevent outdated documentation.* \n`;
  docContent += `*Last Generated: ${new Date().toISOString()}*\n\n`;
  
  docContent += `| Command | Description |\n`;
  docContent += `| :--- | :--- |\n`;
  
  commands.forEach(cmd => {
    docContent += `| \`${cmd.command}\` | ${cmd.description} |\n`;
  });
  
  docContent += `\n\n## 📄 Automated Feature Verification\n`;
  docContent += `- Total documented CLI operations: **${commands.length}**\n`;
  docContent += `- Target CLI entrypoint: \`scripts/cli.js\`\n`;

  if (!fs.existsSync(CLAUDE_DIR)) {
    fs.mkdirSync(CLAUDE_DIR, { recursive: true });
  }

  fs.writeFileSync(DOCS_PATH, docContent, 'utf-8');

  console.log(`${GREEN}✔ Codebase command reference compiled successfully.${RESET}`);
  console.log(`${BOLD}══════════════════════════════════════════════════════════════════════════════════${RESET}`);
  console.log(`📄 Saved reference docs to: ${YELLOW}${DOCS_PATH}${RESET}\n`);
}

main();
